version: "3.8"
services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: tg_bot
    build:
      context: .
    command: python -m main
    volumes:
      - .:/src
    restart: always
    env_file:
      - ".env"
    # Бот стартует после запуска базы
    depends_on:
      - grafana
      - influxdb
    networks:
      - tg_bot

  influxdb:
    image: influxdb:2.1-alpine
    container_name: "test-stats-influxdb"
    restart: always
    volumes:
      - "../influxdb:/var/lib/influxdb"
    ports:
      - "8086:8086"
    env_file:
      - .env

networks:
  tg_bot:
    driver: bridge